### ISSUE TITLE
現在アプリが落ちる不具合について

### ISSUE THREAD

**Issue by vkdlxh** [ohjjoa/SecretMemo#8]
`2019-03-23 23:02:43.248 9590-9590/jp.co.archiveasia.secretmemo E/AndroidRuntime: FATAL EXCEPTION: main
    Process: jp.co.archiveasia.secretmemo, PID: 9590
    java.lang.RuntimeException: Unable to start activity ComponentInfo{jp.co.archiveasia.secretmemo/jp.co.archiveasia.secretmemo.MainActivity}: java.lang.NullPointerException: Attempt to write to field 'java.lang.String jp.co.archiveasia.secretmemo.ItemData.strTitle' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2817)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6541)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
     Caused by: java.lang.NullPointerException: Attempt to write to field 'java.lang.String jp.co.archiveasia.secretmemo.ItemData.strTitle' on a null object reference
        at jp.co.archiveasia.secretmemo.MainActivity.onCreate(MainActivity.java:27)
        at android.app.Activity.performCreate(Activity.java:6975)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1213)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2770)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6541) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767) 
`

アプリを起動すると上記のエラーログがでてすぐアプリが落ちます。
ログの内容を几帳面に読むとどこでエラーが発生するのか把握が出来ます。
エラーの内容はNullPointExceptionです。
ログで問題が発生している箇所はMainActivityの27行目だと教えています。

23行目の`ArrayList<ItemData> oData = new ArrayList();`で
`oItam`ArrayListを作ってますが、
`oItam`配列の中にはまだ値が1個も入ってないです。
その状態でfor文で値を入れようとするので
存在しないモデルに値を入れようとするのは出来ない、
つまりNullPointExceptionが発生すると思います。

説明が難しいと思いますが、
調べても不明な点がございましたら
コメントや連絡ください。

**Comment by vkdlxh** [comment]
一応アプリが起動するようになりましたのでクローズします。
